Bug 1616362 - Avoid unbuffered text I/O, disallowed in py3.
The open call either needs to be binary mode, or buffered.
Since we're redirecting to dev/null anyway it doesn't matter if
it's buffered or not, so let's just make it buffered. Failure
to do this throws:
  ValueError: can't have unbuffered text I/O